"""
Django settings for fikra project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ah8tu%y))a3#+l5$*-u!!#2qb35&kgozb3aqsy%3@s*m@@byh%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['fikra.games', '.localhost', '127.0.0.1', '[::1]']


# Application definition

INSTALLED_APPS = [
    'tinymce',
    'bootstrap_datepicker_plus',
    'croppie',
    'el_pagination',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'nodes',
    'clients',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fikra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fikra.wsgi.application'

X_FRAME_OPTIONS = 'SAMEORIGIN'

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'https://fikra.games/',
    'https://www.fikra.games/',
    'https://games.fikra.games/',
    'http://localhost:3000/',
    'http://127.0.0.1:3000/',
    'http://localhost:8000/',
    'http://127.0.0.1:8000/',
    'http://localhost:5173/',
    'http://127.0.0.1:5173/',
]

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrf-token',
    'x-csrftoken',
    'x-requested-with',
)

CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrf-token',
    'x-csrftoken'
]

# Default locale
LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True

LANGUAGES = (
    ('en-us', 'English (US)'),
    ('ar', 'عربي'),
)

LOCALE_PATHS = [
    os.path.normpath(os.path.join(BASE_DIR, '../fikra', 'locale')),
    os.path.join(BASE_DIR, 'locale'),
]

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CELERY_BROKER_URL = 'amqp://localhost'

TAP_PAYMENT_SECRET_KEY = "sk_test_XKokBfNWv6FIYuTMg5sLPjhJ"
TAP_PAYMENT_MERCHAND_ID = "599424"
TAP_PAYMENT_URL = "https://api.tap.company/v2/charges/"

CURRENCY_3DP = {"BHD", "JOD", "KWD", "OMR"}

LOGIN_REDIRECT_URL = 'clients_dashboard'


NODE_ITEMS_PER_PAGE = 8
HOME_MAX_TAGS = 7
HOME_MAX_CHANNELS = 3
