function loadSave() {
	let save = document.getElementById("savedFiles").value;


	switch (save) {

case "Saved_inkprint":
callibrateID()
loadFolders('inprint', 'graphics/design/colors/inkprint/', 'bg,backprint,paper,printbody,red,yellow,blue,platform,label', '', '', '')

keyParam("src_", count, "graphics/design/colors/inkprint/bg.svg")
keyParam("id_", count, "bg_0")
keyParam("startTime_", count, "0")
keyParam("startPos_", count, "0.5:0.5")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/red.svg")
keyParam("id_", count, "red_4")
keyParam("startTime_", count, "3")
keyParam("startPos_", count, "0.745:1.6")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.9")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,1")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/red.svg")
keyParam("id_", count, "red_4")
keyParam("startTime_", count, "3")
keyParam("startPos_", count, "0.745:1.6")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.9")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,1")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/yellow.svg")
keyParam("id_", count, "yellow_5")
keyParam("startTime_", count, "3")
keyParam("startPos_", count, "0.743:1.6")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.9")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,1")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/blue.svg")
keyParam("id_", count, "blue_6")
keyParam("startTime_", count, "3")
keyParam("startPos_", count, "0.743:1.6")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.9")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,1")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("id_", count, "blue_6")
keyParam("startTime_", count, "4")
keyParam("startPos_", count, "0.5:0.5")
keyParam("type_", count, "basicRotate")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("angle_", count, "25")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("id_", count, "yellow_5")
keyParam("startTime_", count, "4")
keyParam("startPos_", count, "0.5:0.5")
keyParam("type_", count, "basicRotate")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("angle_", count, "1")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("id_", count, "red_4")
keyParam("startTime_", count, "4")
keyParam("startPos_", count, "0.5:0.5")
keyParam("type_", count, "basicRotate")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("angle_", count, "-25")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/backprint.svg")
keyParam("id_", count, "backprint_3")
keyParam("startTime_", count, "1")
keyParam("startPos_", count, "0.32:1.24")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.7")
keyParam("time_", count, "0,0.5")
keyParam("scaleTo_", count, "0.3")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/paper.svg")
keyParam("id_", count, "paper_4")
keyParam("startTime_", count, "2.4")
keyParam("startPos_", count, "0.32:0.82")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.4")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutQuad")
keyParam("fx_", count, "none")
keyParam("fxVal_", count, "0")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/printbody.svg")
keyParam("id_", count, "printbody_5")
keyParam("startTime_", count, "1")
keyParam("startPos_", count, "0.31:1.38")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.7")
keyParam("time_", count, "0,0.5")
keyParam("scaleTo_", count, "0.4")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("id_", count, "paper_4")
keyParam("startTime_", count, "2")
keyParam("startPos_", count, "0.10:0.50")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.20,0.20")
keyParam("y_", count, "0,0.5")
keyParam("time_", count, "0,0,0.4")
keyParam("scaleTo_", count, "0.20,0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/platform.svg")
keyParam("id_", count, "platform_6")
keyParam("startTime_", count, "0.3")
keyParam("startPos_", count, "0.5:1.215")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.29")
keyParam("time_", count, "0,0.6")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/inkprint/label.svg")
keyParam("id_", count, "label_13")
keyParam("startTime_", count, "5")
keyParam("startPos_", count, "0.312:0.898")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0,0.4,0.3")
keyParam("time_", count, "0,0,0.5")
keyParam("scaleTo_", count, "0.0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
break;

case "Saved_rgb":
callibrateID()
loadFolders('print_monitorprinter', 'graphics/design/colors/rgb/', 'bg,monitor,red,green,blue,redblink,greenblink,blueblink,display,pallete,platform,label', '', '', '')
	keyParam("src_", count, "graphics/design/colors/rgb/bg.svg")
	keyParam("id_", count, "bg_0")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.5:0.502")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/monitor.svg")
	keyParam("id_", count, "monitor_5")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.315:1.28")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.779")
	keyParam("time_", count, "0,1")
	keyParam("scaleTo_", count, "0.4")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/platform.svg")
	keyParam("id_", count, "platform_6")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.5:1.215")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.29")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/label.svg")
	keyParam("id_", count, "label_7")
	keyParam("startTime_", count, "2")
	keyParam("startPos_", count, "0.315:0.903")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.4,0.3")
	keyParam("time_", count, "0,0.4,0.6")
	keyParam("scaleTo_", count, "0")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/red.svg")
	keyParam("id_", count, "red_8")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.82:0.60")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,-0.15")
	keyParam("y_", count, "0,-0.3,-0.3")
	keyParam("time_", count, "0,1.8,3")
	keyParam("scaleTo_", count, "0.08")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.8")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/green.svg")
	keyParam("id_", count, "green_9")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.82:0.60")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,-0.05")
	keyParam("y_", count, "0,-0.3,-0.3")
	keyParam("time_", count, "0,1.8,3")
	keyParam("scaleTo_", count, "0.08")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.8")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/blue.svg")
	keyParam("id_", count, "blue_10")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.82:0.60")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,+0.05")
	keyParam("y_", count, "0,-0.3,-0.3")
	keyParam("time_", count, "0,1.8,3")
	keyParam("scaleTo_", count, "0.08")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.8")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/wheel.svg")
	keyParam("id_", count, "pallete_12")
	keyParam("startTime_", count, "10")
	keyParam("startPos_", count, "0.81:1.19")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.8")
	keyParam("time_", count, "0,1")
	keyParam("scaleTo_", count, "0.19")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "3.5")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/redblink.svg")
	keyParam("id_", count, "redblink_8")
	keyParam("startTime_", count, "7")
	keyParam("startPos_", count, "0.667:0.23")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.12,0.04,0.12,0.04,0.12,0.0")
	keyParam("time_", count, " 0,0.5,0.8,1.2,1.5,2,2.3")
	keyParam("scaleTo_", count, "0.00")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "s/e")
	keyParam("fxVal_", count, "1.2,1.3,1.3")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/greenblink.svg")
	keyParam("id_", count, "greenblink_9")
	keyParam("startTime_", count, "7.1")
	keyParam("startPos_", count, "0.769:0.23")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.12,0.04,0.12,0.04,0.12,0.0")
	keyParam("time_", count, " 0,0.5,0.8,1.2,1.5,2,2.3")
	keyParam("scaleTo_", count, "0.00")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "s/e")
	keyParam("fxVal_", count, "1.2,1.3,1.3")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/blueblink.svg")
	keyParam("id_", count, "blueblink_10")
	keyParam("startTime_", count, "7.2")
	keyParam("startPos_", count, "0.874:0.23")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.12,0.04,0.12,0.04,0.12,0.0")
	keyParam("time_", count, " 0,0.5,0.8,1.2,1.5,2,2.3")
	keyParam("scaleTo_", count, "0.00")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "s/e")
	keyParam("fxVal_", count, "1.2,1.3,1.3")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "red_8")
	keyParam("startTime_", count, "11")
	keyParam("startPos_", count, "0.68:0.30")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0.08")
	keyParam("y_", count, "0,0.1")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "green_9")
	keyParam("startTime_", count, "11.1")
	keyParam("startPos_", count, "0.77:0.30")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0.03")
	keyParam("y_", count, "0,0.08")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "blue_10")
	keyParam("startTime_", count, "11.2")
	keyParam("startPos_", count, "0.87:0.30")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,-0.02")
	keyParam("y_", count, "0,0.1")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "pallete_12")
	keyParam("startTime_", count, "10")
	keyParam("startPos_", count, "0.5:0.5")
	keyParam("type_", count, "basicRotate")
	keyParam("time_", count, "0,15")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("angle_", count, "360")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/rgb/display.svg")
	keyParam("id_", count, "display_15")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.315:0.436")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "2")
	gotToNextKey(count + 1)
	break;






case "Saved_alltypes":
callibrateID()
loadFolders('inprint', 'graphics/design/colors/alltypes/', 'bg,monitor,display,backprint,paper1,paper2,printbody,platform,', '', '', '')
	keyParam("src_", count, "graphics/design/colors/alltypes/bg.svg")
	keyParam("id_", count, "bg_0")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.5:0.5")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/backprint.svg")
	keyParam("id_", count, "backprint_3")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.85:1.26")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.7")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.15")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/paper2.svg")
	keyParam("id_", count, "paper_4")
	keyParam("startTime_", count, "4.4")
	keyParam("startPos_", count, "0.85:0.84")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.25")
	keyParam("time_", count, "0,1")
	keyParam("scaleTo_", count, "0.0")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "none")
	keyParam("fxVal_", count, "0")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/printbody.svg")
	keyParam("id_", count, "printbody_5")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.849:1.40")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.7")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.25")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "paper_4")
	keyParam("startTime_", count, "4")
	keyParam("startPos_", count, "0.851:0.52")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.10,0.10")
	keyParam("y_", count, "0,0.25")
	keyParam("time_", count, "0,0,0.4")
	keyParam("scaleTo_", count, "0.10,0")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/backprint.svg")
	keyParam("id_", count, "backprint_5")
	keyParam("startTime_", count, "2")
	keyParam("startPos_", count, "0.580:1.26")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.7")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.15")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/paper1.svg")
	keyParam("id_", count, "paper_6")
	keyParam("startTime_", count, "3.4")
	keyParam("startPos_", count, "0.58:0.84")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.25")
	keyParam("time_", count, "0,1")
	keyParam("scaleTo_", count, "0.0")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "none")
	keyParam("fxVal_", count, "0")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/printbody.svg")
	keyParam("id_", count, "printbody_7")
	keyParam("startTime_", count, "2")
	keyParam("startPos_", count, "0.581:1.40")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.7")
	keyParam("time_", count, "0,0.5")
	keyParam("scaleTo_", count, "0.25")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("id_", count, "paper_6")
	keyParam("startTime_", count, "3")
	keyParam("startPos_", count, "0.30:0.52")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.10,0.10")
	keyParam("y_", count, "0,0.25")
	keyParam("time_", count, "0,0,0.4")
	keyParam("scaleTo_", count, "0.10,0")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/monitor.svg")
	keyParam("id_", count, "monitor_5")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.215:1.30")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.781")
	keyParam("time_", count, "0,1")
	keyParam("scaleTo_", count, "0.4")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutExpo")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/display.svg")
	keyParam("id_", count, "display_15")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.215:0.47")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "2")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/alltypes/platform.svg")
	keyParam("id_", count, "platform_6")
	keyParam("startTime_", count, "0.3")
	keyParam("startPos_", count, "0.5:1.215")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0")
	keyParam("y_", count, "0,-0.29")
	keyParam("time_", count, "0,0.6")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	break;

	case "Saved_colorscheme":
	callibrateID()
	loadFolders('wheel_colorscheme', 'graphics/design/colors/colorwheel/', 'col-1,col-2,col-3,col-4,col-5,col-6,col-7,col-8,col-9,col-10,col-11,col-12', '', '', '')

	keyParam("src_", count, "graphics/design/colors/colorwheel/col-1.svg")
	keyParam("id_", count, "col-1_0")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.61:0.54")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-2.svg")
	keyParam("id_", count, "col-2_1")
	keyParam("startTime_", count, "0.1")
	keyParam("startPos_", count, "0.63:0.62")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-3.svg")
	keyParam("id_", count, "col-3_2")
	keyParam("startTime_", count, "0.2")
	keyParam("startPos_", count, "0.67:0.66")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-4.svg")
	keyParam("id_", count, "col-4_3")
	keyParam("startTime_", count, "0.3")
	keyParam("startPos_", count, "0.72:0.66")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.04,0.04,0.08,0.04")
	keyParam("time_", count, "0,1,1.5,2,2.3")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutCubic")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-5.svg")
	keyParam("id_", count, "col-5_4")
	keyParam("startTime_", count, "0.4")
	keyParam("startPos_", count, "0.77:0.62")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-6.svg")
	keyParam("id_", count, "col-6_5")
	keyParam("startTime_", count, "0.5")
	keyParam("startPos_", count, "0.79:0.54")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-7.svg")
	keyParam("id_", count, "col-7_6")
	keyParam("startTime_", count, "0.6")
	keyParam("startPos_", count, "0.79:0.46")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-8.svg")
	keyParam("id_", count, "col-8_7")
	keyParam("startTime_", count, "0.7")
	keyParam("startPos_", count, "0.77:0.38")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-9.svg")
	keyParam("id_", count, "col-9_8")
	keyParam("startTime_", count, "0.8")
	keyParam("startPos_", count, "0.72:0.34")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-10.svg")
	keyParam("id_", count, "col-10_9")
	keyParam("startTime_", count, "0.9")
	keyParam("startPos_", count, "0.67:0.34")
	keyParam("type_", count, "basicScale")
	keyParam("x_", count, "0.04,0.04,0.08,0.04")
	keyParam("time_", count, "0,1,1.5,2,2.3")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutCubic")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-11.svg")
	keyParam("id_", count, "col-11_10")
	keyParam("startTime_", count, "1.0")
	keyParam("startPos_", count, "0.63:0.38")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/colorwheel/col-12.svg")
	keyParam("id_", count, "col-12_11")
	keyParam("startTime_", count, "1.1")
	keyParam("startPos_", count, "0.61:0.46")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.04")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0.3")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("type_", count, "basicMove")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	break;

case "Saved_schema1":
callibrateID()
loadFolders('pic_schema', 'graphics/design/colors/colorschemepic/', 'bg,pic', '', '', '')
keyParam("src_", count, "graphics/design/colors/colorschemepic/pic.png")
keyParam("id_", count, "pic_0")
keyParam("startTime_", count, "2.9")
keyParam("startPos_", count, "0.5:0.585")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,-0.4,-0.23")
keyParam("y_", count, "0,0,0")
keyParam("time_", count, "0,1,1.8")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorschemepic/bg.svg")
keyParam("id_", count, "bg_1")
keyParam("startTime_", count, "2")
keyParam("startPos_", count, "2:0.5")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,-1")
keyParam("y_", count, "0,0")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-1.svg")
keyParam("id_", count, "col-1_2")
keyParam("startTime_", count, "4.5")
keyParam("startPos_", count, "0.66:0.54")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-2.svg")
keyParam("id_", count, "col-2_3")
keyParam("startTime_", count, "4.6")
keyParam("startPos_", count, "0.68:0.62")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-3.svg")
keyParam("id_", count, "col-3_4")
keyParam("startTime_", count, "4.7")
keyParam("startPos_", count, "0.72:0.66")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-4.svg")
keyParam("id_", count, "col-4_5")
keyParam("startTime_", count, "4.8")
keyParam("startPos_", count, "0.77:0.66")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.04,0.04,0.08,0.04")
keyParam("time_", count, "0,1,1.5,2,2.3")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutCubic")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-5.svg")
keyParam("id_", count, "col-5_6")
keyParam("startTime_", count, "4.9")
keyParam("startPos_", count, "0.82:0.62")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-6.svg")
keyParam("id_", count, "col-6_7")
keyParam("startTime_", count, "5")
keyParam("startPos_", count, "0.84:0.54")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-7.svg")
keyParam("id_", count, "col-7_8")
keyParam("startTime_", count, "5.1")
keyParam("startPos_", count, "0.84:0.46")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-8.svg")
keyParam("id_", count, "col-8_9")
keyParam("startTime_", count, "5.2")
keyParam("startPos_", count, "0.82:0.38")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-9.svg")
keyParam("id_", count, "col-9_10")
keyParam("startTime_", count, "5.3")
keyParam("startPos_", count, "0.77:0.34")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-10.svg")
keyParam("id_", count, "col-10_11")
keyParam("startTime_", count, "5.4")
keyParam("startPos_", count, "0.72:0.34")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.04,0.04,0.08,0.04")
keyParam("time_", count, "0,1,1.5,2,2.3")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutCubic")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-11.svg")
keyParam("id_", count, "col-11_12")
keyParam("startTime_", count, "5.5")
keyParam("startPos_", count, "0.68:0.38")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorwheel/col-12.svg")
keyParam("id_", count, "col-12_13")
keyParam("startTime_", count, "5.6")
keyParam("startPos_", count, "0.66:0.46")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "0.04")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "0.3")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "1")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/design/colors/colorschemepic/label.svg")
keyParam("id_", count, "label_14")
keyParam("startTime_", count, "6.5")
keyParam("startPos_", count, "0.752:0.805")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0,0.4,0.3")
keyParam("time_", count, "0,1,1.3,1.5")
keyParam("scaleTo_", count, "0.0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
break;


case "Saved_hls":
callibrateID()
loadFolders('images_', 'graphics/design/colors/hls/', 'hls0,hls1,hls2,hls3,hls4,hls5,hls6,hls7', '', '', '')
loadFolders('bars_hls', 'graphics/design/colors/hls/', 'huebar,saturationbar,lightnesbar,dot', '', '', '')
	
	keyParam("src_", count, "graphics/design/colors/alltypes/bg.svg")
	keyParam("id_", count, "bg_0")
	keyParam("startTime_", count, "undefined")
	keyParam("startPos_", count, "0.5:0.5")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls0.png")
	keyParam("id_", count, "hls0_1")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls1.png")
	keyParam("id_", count, "hls1_2")
	keyParam("startTime_", count, "2")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls3.png")
	keyParam("id_", count, "hls2_3")
	keyParam("startTime_", count, "7")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "fadeIn")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls2.png")
	keyParam("id_", count, "hls3_4")
	keyParam("startTime_", count, "12")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls4.png")
	keyParam("id_", count, "hls4_5")
	keyParam("startTime_", count, "14")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls5.png")
	keyParam("id_", count, "hls5_6")
	keyParam("startTime_", count, "18")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls7.png")
	keyParam("id_", count, "hls6_7")
	keyParam("startTime_", count, "24")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/hls6.png")
	keyParam("id_", count, "hls7_8")
	keyParam("startTime_", count, "28")
	keyParam("startPos_", count, "0.20:0.50")
	keyParam("type_", count, "basicOpacity")
	keyParam("time_", count, "0,1,2,3,4")
	keyParam("scaleTo_", count, "0.47")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "0,1,1,0")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/huebar.svg")
	keyParam("id_", count, "huebar_9")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.75:0.356")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.3")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/saturationbar.svg")
	keyParam("id_", count, "saturationbar_10")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.748:0.572")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.3")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/lightnesbar.svg")
	keyParam("id_", count, "lightnesbar_11")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.75:0.797")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "0.3")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/dot.svg")
	keyParam("id_", count, "dot_12")
	keyParam("startTime_", count, "1")
	keyParam("startPos_", count, "0.773:0.313")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0,0.08,0.08,0,0,-0.08,-0.08,0")
	keyParam("y_", count, "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0")
	keyParam("time_", count, "0,1,2,3,3.5,5,6.3,8,8.5,9.5")
	keyParam("scaleTo_", count, "0.02")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/dot.svg")
	keyParam("id_", count, "dot_13")
	keyParam("startTime_", count, "13")
	keyParam("startPos_", count, "0.767:0.527")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0,0.08,0.08,0,0,-0.08,-0.08,0")
	keyParam("y_", count, "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0")
	keyParam("time_", count, "0,1,2,2.5,3.3,4.3,5.6,7,8,9")
	keyParam("scaleTo_", count, "0.02")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/colors/hls/dot.svg")
	keyParam("id_", count, "dot_14")
	keyParam("startTime_", count, "23")
	keyParam("startPos_", count, "0.767:0.752")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0,0.08,0.08,0,0,-0.08,-0.08,0")
	keyParam("y_", count, "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0")
	keyParam("time_", count, "0,1,2,3,3.5,5,6,7,7.5,8.8")
	keyParam("scaleTo_", count, "0.02")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutQuad")
	keyParam("fx_", count, "fadeIn")
	keyParam("fxVal_", count, "1")
	gotToNextKey(count + 1)
	break;

	
case "Saved_whitespace":
callibrateID()
loadFolders('whitespace_whitespace','graphics/design/interactions/compositing/whitespace/','bg,watermark,baloon,cloud,cloud','','','')
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/bg.svg")
keyParam("id_",count,"bg_0")
keyParam("startTime_",count,"0")
keyParam("startPos_",count,"0.5:0.5")
keyParam("type_",count,"basicMove")
keyParam("scaleTo_",count,"1")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"none")
keyParam("fx_",count,"none")
 gotToNextKey(count+1)
 addUI()
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/watermark.svg")
keyParam("id_",count,"watermark_1")
keyParam("startTime_",count,"6")
keyParam("startPos_",count,"0.0000:0.00")
keyParam("type_",count,"basicMove")
keyParam("x_",count,"0,0.065")
keyParam("y_",count,"0,0.132")
keyParam("time_",count,"0,1")
keyParam("scaleTo_",count,"0.15")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"easeOutQuad")
keyParam("fx_",count,"none")
 gotToNextKey(count+1)
 addUI()
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/cloud.svg")
keyParam("id_",count,"cloud_2")
keyParam("startTime_",count,"0")
keyParam("startPos_",count,"0.445:0.474")
keyParam("type_",count,"basicMove")
keyParam("x_",count,"0,0.1")
keyParam("y_",count,"0,0")
keyParam("time_",count,"0,6")
keyParam("scaleTo_",count,"0.08")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"easeOutQuad")
keyParam("fx_",count,"fadeIn")
keyParam("fxVal_",count,"1.5")
 gotToNextKey(count+1)
 addUI()
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/cloud.svg")
keyParam("id_",count,"cloud_3")
keyParam("startTime_",count,"0")
keyParam("startPos_",count,"0.55:0.437")
keyParam("type_",count,"basicMove")
keyParam("x_",count,"0,-0.1")
keyParam("y_",count,"0,0")
keyParam("time_",count,"0,6")
keyParam("scaleTo_",count,"0.06")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"easeOutQuad")
keyParam("fx_",count,"fadeIn")
keyParam("fxVal_",count,"1.5")
 gotToNextKey(count+1)
 addUI()
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/baloon.svg")
keyParam("id_",count,"baloon_4")
keyParam("startTime_",count,"1")
keyParam("startPos_",count,"0.521:1.398")
keyParam("type_",count,"basicMove")
keyParam("x_",count,"0,0,0,0,0")
keyParam("y_",count,"0,-1.1,-0.9,-1.05,-1")
keyParam("time_",count,"0,2,3,4,5")
keyParam("scaleTo_",count,"0.14")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"easeInOutQuad")
keyParam("fx_",count,"fadeIn")
keyParam("fxVal_",count,"1.2")
 gotToNextKey(count+1)
 addUI()
keyParam("src_",count,"graphics/design/interactions/compositing/whitespace/embracetxt.svg")
keyParam("id_",count,"text_5")
keyParam("startTime_",count,"4")
keyParam("startPos_",count,"0.474:0.765")
keyParam("type_",count,"basicMove")
keyParam("x_",count,"0,0")
keyParam("y_",count,"0,-0.1")
keyParam("time_",count,"0,2")
keyParam("scaleTo_",count,"0.2")
keyParam("anchor_",count,"0.5,0.5")
keyParam("opac_",count,"1")
keyParam("shape_",count,"-")
keyParam("ease_",count,"easeInOutQuad")
keyParam("fx_",count,"fadeIn")
keyParam("fxVal_",count,"1")
 gotToNextKey(count+1)
break;

	case "Saved_bettererah":
	callibrateID()
	loadFolders('ber_bettererah', 'graphics/design/interactions/compositing/bettererah/', 'bg,watermark,box,box,erah1,erah2', '', '', '')
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/bg.svg")
	keyParam("id_", count, "bg_0")
	keyParam("startTime_", count, "0")
	keyParam("startPos_", count, "0.5:0.5")
	keyParam("type_", count, "basicMove")
	keyParam("scaleTo_", count, "1")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "none")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/watermark.svg")
	keyParam("id_", count, "watermark_1")
	keyParam("startTime_", count, "1.7")
	keyParam("startPos_", count, "0.0000:0.00")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0.065")
	keyParam("y_", count, "0,0.132")
	keyParam("time_", count, "0,0.6")
	keyParam("scaleTo_", count, "0.15")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeOutQuad")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/box.svg")
	keyParam("id_", count, "box_2")
	keyParam("startTime_", count, "1.1")
	keyParam("startPos_", count, "0.329:1.504")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0")
	keyParam("y_", count, "0,-1.2,-1")
	keyParam("time_", count, "0,1,1.5")
	keyParam("scaleTo_", count, "0.3")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutCubic")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/box.svg")
	keyParam("id_", count, "box_3")
	keyParam("startTime_", count, "1.2")
	keyParam("startPos_", count, "0.665:1.504")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0")
	keyParam("y_", count, "0,-1.2,-1")
	keyParam("time_", count, "0,1,1.5")
	keyParam("scaleTo_", count, "0.3")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutCubic")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/erarh1.svg")
	keyParam("id_", count, "erarh1_4")
	keyParam("startTime_", count, "1.45")
	keyParam("startPos_", count, "0.331:1.496")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0")
	keyParam("y_", count, "0,-1.2,-1")
	keyParam("time_", count, "0,1,1.5")
	keyParam("scaleTo_", count, "0.2")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutCubic")


	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	addUI()
	keyParam("src_", count, "graphics/design/interactions/compositing/bettererah/erarh2.svg")
	keyParam("id_", count, "erarh2_5")
	keyParam("startTime_", count, "1.65")
	keyParam("startPos_", count, "0.668:1.5")
	keyParam("type_", count, "basicMove")
	keyParam("x_", count, "0,0,0")
	keyParam("y_", count, "0,-1.2,-1")
	keyParam("time_", count, "0,1,1.5")
	keyParam("scaleTo_", count, "0.2")
	keyParam("anchor_", count, "0.5,0.5")
	keyParam("opac_", count, "1")
	keyParam("shape_", count, "-")
	keyParam("ease_", count, "easeInOutCubic")
	keyParam("fx_", count, "none")
	gotToNextKey(count + 1)
	break;

				case "Saved_colorscheme":
				callibrateID()
				loadFolders('wheel_colorscheme', 'graphics/design/colors/colorwheel/', 'col-1,col-2,col-3,col-4,col-5,col-6,col-7,col-8,col-9,col-10,col-11,col-12', '', '', '')
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-1.svg")
				keyParam("id_", count, "col-1_0")
				keyParam("startTime_", count, "0")
				keyParam("startPos_", count, "0.61:0.54")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-2.svg")
				keyParam("id_", count, "col-2_1")
				keyParam("startTime_", count, "0.1")
				keyParam("startPos_", count, "0.63:0.62")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-3.svg")
				keyParam("id_", count, "col-3_2")
				keyParam("startTime_", count, "0.2")
				keyParam("startPos_", count, "0.67:0.66")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-4.svg")
				keyParam("id_", count, "col-4_3")
				keyParam("startTime_", count, "0.3")
				keyParam("startPos_", count, "0.72:0.66")
				keyParam("type_", count, "basicScale")
				keyParam("x_", count, "0.04,0.04,0.08,0.04")
				keyParam("time_", count, "0,1,1.5,2,2.3")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "1")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "easeOutCubic")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-5.svg")
				keyParam("id_", count, "col-5_4")
				keyParam("startTime_", count, "0.4")
				keyParam("startPos_", count, "0.77:0.62")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-6.svg")
				keyParam("id_", count, "col-6_5")
				keyParam("startTime_", count, "0.5")
				keyParam("startPos_", count, "0.79:0.54")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-7.svg")
				keyParam("id_", count, "col-7_6")
				keyParam("startTime_", count, "0.6")
				keyParam("startPos_", count, "0.79:0.46")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-8.svg")
				keyParam("id_", count, "col-8_7")
				keyParam("startTime_", count, "0.7")
				keyParam("startPos_", count, "0.77:0.38")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-9.svg")
				keyParam("id_", count, "col-9_8")
				keyParam("startTime_", count, "0.8")
				keyParam("startPos_", count, "0.72:0.34")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-10.svg")
				keyParam("id_", count, "col-10_9")
				keyParam("startTime_", count, "0.9")
				keyParam("startPos_", count, "0.67:0.34")
				keyParam("type_", count, "basicScale")
				keyParam("x_", count, "0.04,0.04,0.08,0.04")
				keyParam("time_", count, "0,1,1.5,2,2.3")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "1")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "easeOutCubic")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-11.svg")
				keyParam("id_", count, "col-11_10")
				keyParam("startTime_", count, "1.0")
				keyParam("startPos_", count, "0.63:0.38")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("src_", count, "graphics/design/colors/colorwheel/col-12.svg")
				keyParam("id_", count, "col-12_11")
				keyParam("startTime_", count, "1.1")
				keyParam("startPos_", count, "0.61:0.46")
				keyParam("type_", count, "basicMove")
				keyParam("scaleTo_", count, "0.04")
				keyParam("anchor_", count, "0.5,0.5")
				keyParam("opac_", count, "0.3")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				addUI()
				keyParam("type_", count, "basicMove")
				keyParam("shape_", count, "-")
				keyParam("ease_", count, "none")
				keyParam("fx_", count, "fadeIn")
				keyParam("fxVal_", count, "1")
				gotToNextKey(count + 1)
				break;

	case "Saved_africa":
	callibrateID()
	loadFolders('afrika_', 'graphics/general/enviroment/afrika_water/', 'afrika,tap', 'drop', '', '')
addUI()
keyParam("type_", count, "basicMove")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
shapeParam(count, '#fff6d2', 0.5, 0.5)
keyParam("id_", count, "rect_0")
keyParam("startTime_", count, "0")
keyParam("startPos_", count, "0.5:0.5")
keyParam("type_", count, "basicMove")
keyParam("scaleTo_", count, "1.2")
keyParam("anchor_", count, "0.5:0.5")
keyParam("opac_", count, "1")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/afrika_water/afrika.svg")
keyParam("id_", count, "afrika_2")
keyParam("startTime_", count, "0")
keyParam("startPos_", count, "0.338:0.509")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.4,0.3")
keyParam("time_", count, "0,1,1.2")
keyParam("scaleTo_", count, "0.0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutSine")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/afrika_water/tap.svg")
keyParam("id_", count, "tap_3")
keyParam("startTime_", count, "1")
keyParam("startPos_", count, "1.35:0.41")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,-0.5")
keyParam("y_", count, "0,0")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.3")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutCubic")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/afrika_water/drop.svg")
keyParam("id_", count, "drop_4")
keyParam("startTime_", count, "3")
keyParam("startPos_", count, "0.722:0.538")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.05")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "0.2")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/afrika_water/drop.svg")
keyParam("id_", count, "drop_5")
keyParam("startTime_", count, "4")
keyParam("startPos_", count, "0.732:0.538")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.035")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "0.3")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/afrika_water/drop.svg")
keyParam("id_", count, "drop_6")
keyParam("startTime_", count, "5")
keyParam("startPos_", count, "0.725:0.538")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "0.035")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "fadeIn")
keyParam("fxVal_", count, "0.3")
gotToNextKey(count + 1)
break;


case "Saved_water":
callibrateID()
loadFolders('water_water', 'graphics/general/enviroment/water/', 'logo,sign,wave1,wave2,wave3,wave4', '', '', '')
addUI()
shapeParam(count, '#cff5ff', 0.5, 1)
keyParam("id_", count, "rect_0")
keyParam("startTime_", count, "0")
keyParam("startPos_", count, "0.5:3.0")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0.0,0.0")
keyParam("y_", count, "0.00,-1.5")
keyParam("time_", count, "0.3,0.8")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("ease_", count, "easeOutExpo")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("id_", count, "rect_0")
keyParam("startTime_", count, "0")
keyParam("startPos_", count, "0.5:3.0")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0.0,0.0")
keyParam("y_", count, "-1.5,0.0")
keyParam("time_", count, "7.70,5.00")
keyParam("scaleTo_", count, "1")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("startTime_", count, "1")
keyParam("type_", count, "basicMove")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("type_", count, "basicMove")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("type_", count, "basicMove")
keyParam("shape_", count, "-")
keyParam("ease_", count, "none")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/wave1.svg")
keyParam("id_", count, "wave1")
keyParam("startTime_", count, "1")
keyParam("startPos_", count, "0.5:1.297")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "1.2")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutExpo")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/wave2.svg")
keyParam("id_", count, "wave2")
keyParam("startTime_", count, "1.3")
keyParam("startPos_", count, "0.52:1.304")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "1.2")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutExpo")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/wave3.svg")
keyParam("id_", count, "wave3")
keyParam("startTime_", count, "1.6")
keyParam("startPos_", count, "0.548:1.447")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "1.2")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutExpo")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/wave4.svg")
keyParam("id_", count, "wave4")
keyParam("startTime_", count, "1.8")
keyParam("startPos_", count, "0.545:1.621")
keyParam("type_", count, "basicMove")
keyParam("x_", count, "0,0")
keyParam("y_", count, "0,-0.6")
keyParam("time_", count, "0,1")
keyParam("scaleTo_", count, "1.2")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeOutExpo")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/logo.svg")
keyParam("id_", count, "logo_9")
keyParam("startTime_", count, "1")
keyParam("startPos_", count, "0.5:0.386")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.20,0.15")
keyParam("time_", count, "0,1,1.2")
keyParam("scaleTo_", count, "0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutQuad")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
addUI()
keyParam("src_", count, "graphics/general/enviroment/water/sign.svg")
keyParam("id_", count, "sign_10")
keyParam("startTime_", count, "2")
keyParam("startPos_", count, "0.5:0.627")
keyParam("type_", count, "basicScale")
keyParam("x_", count, "0.70,0.55")
keyParam("time_", count, "0,0.7,0.8")
keyParam("scaleTo_", count, "0")
keyParam("anchor_", count, "0.5,0.5")
keyParam("opac_", count, "1")
keyParam("shape_", count, "-")
keyParam("ease_", count, "easeInOutSine")
keyParam("fx_", count, "none")
gotToNextKey(count + 1)
break;













	}




}